[project]
name = "slack-client-impl"
version = "0.1.0"
requires-python = ">=3.12"
description = "Slack implementation of chat client"
dependencies = [
    "chat-client-api",
    "slack-sdk>=3.33.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
