[project]
name = "chat-client-api"
version = "0.1.0"
requires-python = ">=3.12"
description = "Abstract interface for chat clients"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
